theme: jekyll-theme-minimal
title: CheckFake
description: CheckFake vise à vous proposer des informations complémentaires aux articles d'informations que vous lisez sur internet en vous fournissant un niveau de confiance sur le contenu que vous avez devant les yeux.
logo: logo.svg
